"""empty message

Revision ID: 37d191709aab
Revises: 73292a3cdda3
Create Date: 2020-09-18 11:08:08.480353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d191709aab'
down_revision = '73292a3cdda3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('follows', sa.Column('update_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follows', 'update_at')
    op.drop_column('follows', 'created_at')
    # ### end Alembic commands ###
