"""empty message

Revision ID: c2f1938f0ec1
Revises: 6cc8950e44f4
Create Date: 2020-09-16 11:51:29.532096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f1938f0ec1'
down_revision = '6cc8950e44f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('wine_indeces', table_name='wines')
    op.create_index('wine_indeces', 'wines', ['wine_type', 'avg_price', 'name', 'color', 'verietal', 'country', 'community_rank', 'pairings'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('wine_indeces', table_name='wines')
    op.create_index('wine_indeces', 'wines', ['wine_type', 'avg_price', 'name', 'color', 'verietal', 'country', 'community_rank', 'pairings', 'description'], unique=False)
    # ### end Alembic commands ###
